### ISSUE TITLE
Notification for @afaerber

### ISSUE THREAD

**Issue by ThomasKaiser** [BPI-SINOVOIP/BPI-W2-bsp#1]
@afaerber I thought I try it this way too. Now in this repo RealTek's BSP is available based on a 4.9.119 and u-boot 2015.7 -- so in case you're still working on mainline support for the SoCs maybe fork the repo right now...

**Comment by noralee** [comment]
@ThomasKaiser i'd like to give you a gift - W2, can you provide me your address and phone no by nora.sh.lee63@gmail.com?

**Comment by parrotgeek1** [comment]
@ThomasKaiser the code quality isn't even that bad either

**Comment by parrotgeek1** [comment]
@ThomasKaiser I am somewhat wrong in my initial assessment. The platform code is fine (uses 100% device trees, very clean) but the video/audio/decoder drivers are just horrifying. Almost like 2 different teams.

**Comment by afaerber** [comment]
Thanks @ThomasKaiser, I'm aware.
