### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by michal5520pl** [BPI-SINOVOIP/BPI-W2-bsp#2]
![build-bananapi-error](https://user-images.githubusercontent.com/21153594/46169969-029f3b80-c28c-11e8-834f-b5585e7537a3.png)
Hello!

I tried to build the kernel by build.sh, but it throws errors on the screen "No such file or directory".
There is no execv and there are doubled slashes.

Greetings,
Michal.

**Comment by Jimx-** [comment]
`toolchains/asdk64-4.9.4-a53-EL-3.10-g2.19-a64nt-160307/bin/aarch64-linux-xgcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.2.5, with debug_info, not stripped
`

The executables in the provided toolchain are 32-bit. If you are using 64-bit system, you might have to install 32-bit libraries needed by the executables, e.g. `libc6-i386` on ubuntu.

**Comment by michal5520pl** [comment]
That has resolved my problem, thank you
