### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tiev0li** [BPI-SINOVOIP/BPI-W2-bsp#9]
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-ld.bfd   -r -o image/rtd1295/src/app/libbootload.o image/rtd1295/src/app/bootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .v_entry=image/rtd1295/v_entry.img image/rtd1295/src/app/libbootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .exc_redirect=image/rtd1295/exc_redirect.img image/rtd1295/src/app/libbootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .exc_dispatch=image/rtd1295/exc_dispatch.img image/rtd1295/src/app/libbootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .isrvideoimg=image/rtd1295/isr_video.img image/rtd1295/src/app/libbootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .rosbootvectorimg=image/rtd1295/ros_bootvector.img image/rtd1295/src/app/libbootload.o
/home/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objcopy --add-section .a_entry=image/rtd1295/a_entry.img image/rtd1295/src/app/libbootload.o
  LD      u-boot
common/built-in.o: In function `GET_KF_IN_OTP':
/home/BPI-W2-bsp/u-boot-rtk/common/cmd_rpmb.c:1081: undefined reference to `OTP_Get_Byte'
Segmentation fault (core dumped)
Makefile:1289: recipe for target 'u-boot' failed
make[1]: *** [u-boot] Error 139
make[1]: Leaving directory '/home/BPI-W2-bsp/u-boot-rtk'
Makefile:36: recipe for target 'u-boot' failed
make: *** [u-boot] Error 2

**Comment by pablo-new17** [comment]
Hi,
May we know your compile environment ?
Mine is Ubuntu 16.04(64 bit) and I have no problem to build W2

tiev0li <notifications@github.com> 於 2019年10月20日 週日 18:18 寫道：

**Comment by tiev0li** [comment]
use readme docker images  16.04.

**Comment by Dangku** [comment]
@tiev0li https://github.com/BPI-SINOVOIP/BPI-W2-bsp/commit/6e6aefc35dc50b1b8231cdb03a995d088f29eb21
